### ISSUE TITLE
Creating a blank user prevents the dashboard from showing up

### ISSUE THREAD

**Issue by zachp98** [co-op-dev/INFO-442-Project#10]
When I created a user with no first or last name and no house name, the user showed up as NAN and the dashboard had nothing on it but a small blank box.

Reproduction steps:
1. Click Sign Up
2. Enter b@b.edu into the email field
3. Enter 123456 into the password field
4. Press Sign Up
5. Click on the user bubble in the top right corner of the screen which should say 'NAN'

**Comment by rioishii** [comment]
Fixed. Made all input field in the sign in "required" so a user cannot sign up with missing information.
