### ISSUE TITLE
Minor: Buttons inaccessible at different screen sizes

### ISSUE THREAD

**Issue by maps101** [co-op-dev/INFO-442-Project#11]
The "new chore" button is not able to be clicked on when the page is shrunk because the title of the page covers the button, as is able to be seen in the screenshot. At screen sized 768px and smaller the new chore button is not accessible. This trend continues at even smaller screen sizes.

To reproduce:
1. Login
2. Select browser window and condense to 768px or less
3. Try and select "new chore" button
OR
2. Right click and select inspect page
3. Choose new screen size as "tablet" or "mobile"
4. Select "new chore button"

<img width="582" alt="Screen Shot 2019-06-10 at 6 49 36 PM" src="https://user-images.githubusercontent.com/35041191/59238097-75014300-8bb1-11e9-9e0a-e919c1c87a36.png">

**Comment by rioishii** [comment]
This application was meant for a desktop browser and we did not have requirements to be mobile/tablet friendly.
