### ISSUE TITLE
A blank chore can be created

### ISSUE THREAD

**Issue by rheaxychen** [co-op-dev/INFO-442-Project#12]
![image](https://user-images.githubusercontent.com/24926110/59240317-d37def80-8bb8-11e9-836c-a7369555251c.png)

The above picture shows a chore without any description. 

Steps:
1. Chore name cannot be blank
2. If blank, prevent the user from creating it.
3. If the chore with the same name exists, warn the user when creating it.

**Comment by rioishii** [comment]
Minor design issue. Made the chore name required.
