### ISSUE TITLE
Only showing up users in History Tab

### ISSUE THREAD

**Issue by rheaxychen** [co-op-dev/INFO-442-Project#15]
![image](https://user-images.githubusercontent.com/24926110/59241803-efd05b00-8bbd-11e9-8d4f-813ec0ea59e1.png)

As a user, my assumption of the History Tab is to show all the past activities. I am unable to add a user into the house or see my user activities on the History Tab.

**Comment by rioishii** [comment]
The history tab was designed to show only the completed chores in the house. It does not have the capability of showing other user activities.
