### ISSUE TITLE
No way to clear history

### ISSUE THREAD

**Issue by aliar97** [co-op-dev/INFO-442-Project#19]
I would say this is a minor bug. Eventually the history gets very cluttered, it ends up not entirely fitting on the screen. There should be a way to clear your history. Try adding more and more things into the history, when you do it gets to the point where you don't want to be able to see some of the things you did 6 months ago for a chore.

**Comment by rioishii** [comment]
Clearing history is not in our requirements, thus we did not implement that feature.
