### ISSUE TITLE
Year value when picking date for Create New Chore

### ISSUE THREAD

**Issue by s21dy** [co-op-dev/INFO-442-Project#20]
This is a really really really really minor thing to say but I want to point out that it would be nice if you can include the year value when user if picking the Due Date for new chore. 
Also you I believe someone have mention this but you should restrict your user to input the blank name otherwise it will showing nothing when picking the "Assign To"

![Screen Shot 2019-06-10 at 10 54 37 PM](https://user-images.githubusercontent.com/43624825/59246955-c110af80-8bd2-11e9-883d-0eb23c1b8d38.png)

**Comment by rioishii** [comment]
We thought about including years in the date picker but our group decided it was more appropriate to not include the year for better design.
