### ISSUE TITLE
No way to add roommate? 

### ISSUE THREAD

**Issue by my828** [co-op-dev/INFO-442-Project#21]
I couldn't figure out how to add a roommate to my house... I could only assign chores to myself. :/
<img width="878" alt="p" src="https://user-images.githubusercontent.com/32341631/59247186-5e6be380-8bd3-11e9-82c3-bc31b53c98c3.png">

**Comment by rioishii** [comment]
Other user in the house must sign up with the same house name as you. We have not implemented a feature where you can add someone from the dashboard.
