### ISSUE TITLE
Name overflows when too long.

### ISSUE THREAD

**Issue by matthewkli97** [co-op-dev/INFO-442-Project#24]
Text overflows container when the name is too long. See image for reference.

Reproduction Steps:

1. Click create new user
2. Enter a long name into the name input.
3. Enter the rest of the credentials correctly.
4. Click Submit

<img width="1303" alt="Screen Shot 2019-06-11 at 12 08 10 AM" src="https://user-images.githubusercontent.com/26758656/59250757-076b0c00-8bdd-11e9-886b-688b07e93a81.png">

**Comment by rioishii** [comment]
Fixed. Set first name and last name lax length to 20.
