### ISSUE TITLE
Long name overflows in 'assigned' section of chore card

### ISSUE THREAD

**Issue by matthewkli97** [co-op-dev/INFO-442-Project#27]
Reproduction:
1. Create an account with a long name
2. Create a chore
3. See chore overflows. 

<img width="1299" alt="Screen Shot 2019-06-11 at 12 09 14 AM" src="https://user-images.githubusercontent.com/26758656/59251255-4057b080-8bde-11e9-80ee-2b623e91d27e.png">

**Comment by rioishii** [comment]
Fixed. Set first and last name max length to 20.
