### ISSUE TITLE
Not able to remove chore card from the history sometimes

### ISSUE THREAD

**Issue by navjanar1** [co-op-dev/INFO-442-Project#29]
1. Logged into app
2. Click "History" button
3. Click “x” button on the “test” chore to permanently remove it from history (I assume)
4. App does not do anything when I click the “YES” button on the confirmation popup

**Comment by rioishii** [comment]
Cannot replicate issue. We do not have a "x" button on the chore card. Users are not able to remove completed chores from the history page.
