### ISSUE TITLE
some cards do not have an “X” to delete them from the history of cards

### ISSUE THREAD

**Issue by navjanar1** [co-op-dev/INFO-442-Project#30]
![Screen Shot 2019-06-11 at 2 04 43 AM](https://user-images.githubusercontent.com/37914670/59258722-59b42900-8bed-11e9-82b5-feea609086a2.png)

Even though card is rendered with odd text, it should have "X" button to be able to delete the chore permanently from the list of history chores

**Comment by rioishii** [comment]
You can only remove users from the history tab, not the chore card itself.
