### ISSUE TITLE
Chores disappear after logging in and out few times

### ISSUE THREAD

**Issue by navjanar1** [co-op-dev/INFO-442-Project#32]
All chores disappear after logging in and logging out a few times (4 times in my case), and my user disappears (no user image icon visible)
![Screen Shot 2019-06-11 at 2 15 12 AM](https://user-images.githubusercontent.com/37914670/59259518-ced42e00-8bee-11e9-9f07-2ef025e0b528.png)

**Comment by rioishii** [comment]
Could not replicate this issue. Logged out and back in over 10 times.
