### ISSUE TITLE
Name can contain numbers or symbols

### ISSUE THREAD

**Issue by jinc132** [co-op-dev/INFO-442-Project#34]
Minor: when I select sign up and enter into the first name input box it can include symbols or numbers. Moreover, when I enter a none existing email in the sign up, it does not check whether it is a valid email or not. For instance, whether it is a yahoo, gmail, or a comcast email. This is a minor bug since it is a verification.

**Comment by rioishii** [comment]
Our requirements was that the input field can be any UTF-8 characters. As for valid email, that is not something we can verify since the Firebase user authentication cannot check if the email is valid or not.
