### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by yiranni** [co-op-dev/INFO-442-Project#36]
Maybe some enhancements on sorting?
All chores are sorted by added time, maybe there should be some ways to sort by due dates? 
Because there is no way for the users to find all the chores that are due on the same day.
![image](https://user-images.githubusercontent.com/32496771/59306819-fdcfbb80-8c51-11e9-8a29-00fefa7107fe.png)

**Comment by rioishii** [comment]
Sorting by due dates is not in our requirements, thus did not implement this feature.
